apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.logparser.name }}
  namespace: {{ .Values.logparser.namespace }}
  labels:
    app: logparser
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: logparser
    spec:
      template:
        spec:
          containers:
            - name: cmg-logparser
              image: ocroso/cmg-logparser:latest
              ports:
              - containerPort: 80
          restartPolicy: OnFailure
